services:
  api:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20.11.1
    container_name: steel-api
    ports:
      - "3000:3000"
      - "9223:9223"
    volumes:
      - ./.cache:/app/.cache
    networks:
      - steel-network

  ui:
    container_name: steel-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_WS_URL: ${VITE_WS_URL}
        VITE_OPENAPI_URL: ${VITE_OPENAPI_URL}
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_WS_URL=${VITE_WS_URL}
      - VITE_OPENAPI_URL=${VITE_OPENAPI_URL}
    depends_on:
      - api
    networks:
      - steel-network

networks:
  steel-network:
    name: steel-network
    driver: bridge
